youdu/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('youdu.core.views',
	url(r'^$', 'home', name='home'),
	url(r'^submit/$', 'submit_poster'),
	url(r'^posters/(?P<poster_id>\d+)/$', 'show_poster'),
	url(r'^badlink/$', 'bad_link'),
	
    # url(r'^sanren/', include('sanren.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('',
	url(r'^login/renren/$', 'youdu.core.renren.renren_login'),
	url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
)

if settings.DEBUG:
	urlpatterns += patterns('',
		url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
		url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
	)

youdu/core/models.py
# encoding: utf-8
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

class UserProfile(models.Model):
	user = models.OneToOneField(User, verbose_name=_(u'用户'), related_name="user_profile")
	email = models.EmailField(_(u"联系邮箱"), blank=True)
	phone = models.CharField(_(u'联系电话'), max_length=20, blank=True)
	self_intro = models.CharField(_(u'个人简介'), max_length=200, blank = True)
	avatar = models.CharField(_(u'个人头像'), max_length=200, blank=True)
	small_avatar = models.CharField(_(u'个人小头像'), max_length=200, blank=True)
	modify_at = models.DateTimeField(auto_now = True)

EVENT_TYPES = (
    (u'讲座', u'讲座'),
    (u'讨论会/沙龙', u'讨论会/沙龙'),
    (u'宣讲会', u'宣讲会'),
)
class Event(models.Model):
	user_post = models.ForeignKey(User, verbose_name=_(u'发布人'))
	type = models.CharField(_(u'类型'), max_length=10)
	title = models.CharField(_(u'标题'), max_length=25)
	site = models.CharField(_(u'地点'), max_length=50)
	start_time = models.DateTimeField(_(u'开始时间'))
	create_at = models.DateTimeField(auto_now_add = True)
	modify_at = models.DateTimeField(auto_now = True)
	poster = models.ImageField(upload_to='posters/%Y/%m/%d')
	small_poster = models.ImageField(upload_to='thumbnails/%Y/%m/%d')
	link = models.URLField()
	designer = models.CharField(_(u'设计者'), max_length=20)

class Event_User(models.Model):
	event = models.ForeignKey(Event, verbose_name=_(u'活动'))
	user = models.ForeignKey(User, verbose_name=_(u'用户'))
	join_date = models.DateField(_(u'状态变更时间'), auto_now = True)
	is_admin = models.BooleanField(_(u'活动管理员'), default = False)
	is_join = models.BooleanField(_(u'参加'), default=False)

youdu/core/forms.py
# encoding: utf-8
from django import forms
from django.db import models
from django.forms import ModelForm, TextInput
from django.utils.translation import ugettext_lazy as _

from youdu.core.models import *
		
class EventCreationForm(ModelForm):
	type = forms.ChoiceField(label=_(u"活动类型"),choices=EVENT_TYPES)
	title = forms.CharField(label=_(u"活动名称"),max_length=25,min_length=4,
		widget=forms.TextInput(attrs={'class': 'input-xlarge'}), required=True)
	site = forms.CharField(label=_(u"活动地点"),max_length=50,
		widget=forms.TextInput(attrs={'class': 'input-xlarge'}), required=True)
	start_time = forms.DateTimeField(label=_(u"活动时间"), required=True)
	link = forms.CharField(label=_(u"详情链接"),max_length=100,
		widget=forms.TextInput(attrs={'class': 'input-xlarge'}), required=False)
	designer = forms.CharField(label=_(u"设计者名称"),max_length=20,
		widget=forms.TextInput(attrs={'class': 'input-xlarge'}), required=True)
	poster = forms.ImageField(required=True)
	
	class Meta:
		model = Event
		fields = ('type','title','site','link','start_time','designer','poster')

youdu/core/views.py
# encoding: utf-8
import datetime
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.http import Http404
from django.shortcuts import render_to_response
from django.template import *
from django.core.exceptions import *

from django.core.files.images import ImageFile

from youdu.core.forms import *
from youdu.core.helper import *


def home(request):
	today = datetime.date.today()
	delta = datetime.timedelta(days=7)
	recent = today + delta
	later = recent + delta
	
	recent_events = Event.objects.filter(start_time__gte=today, start_time__lte=recent).order_by('start_time')
	#recent_events = Event.objects.all()
	return render_to_response('index.html', {'recent_events':recent_events,'today':today,'recent':recent,'later':later}, context_instance=RequestContext(request))
	
def submit_poster(request):
	if request.method == 'GET':
		form = EventCreationForm()
	elif request.method == 'POST':
		form = EventCreationForm(request.POST, request.FILES)
		print request.FILES['poster']
		if form.is_valid():
			new_event = form.save(commit=False)
			new_event.user_post = request.user
			img_file = get_thumbnail(request.FILES['poster'], request.FILES['poster'].name)
			new_event.small_poster.save(request.FILES['poster'].name, img_file, save=False)
			new_event.save()
			print 'saved'
			return HttpResponseRedirect('/')
	return render_to_response('submit_poster.html', {'form':form},context_instance=RequestContext(request))
	
def show_poster(request, poster_id):
	try:
		event = Event.objects.get(id=poster_id)
	except Event.DoesNotExist:
		raise Http404
	return render_to_response('poster.html', {'event':event},context_instance=RequestContext(request))
	
	

youdu/core/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>	
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Helium Chen">

    <!-- Le styles -->
    <link href="/static/css/bootstrap.css" rel="stylesheet">
    <link href="/static/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="/static/css/style.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="./ico/favicon.ico">
	{% block extra_head %}{% endblock %}
  </head>

  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">有堵墙 <span class="badge">beta1.0</span></a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="/">主墙</a></li>
              <li><a href="/about">关于</a></li>
		<li><a href="#">订阅海报</a></li>
		<li><a><i class="icon-map-marker icon-white"></i> 清华大学</a></li>
            </ul>
		<ul class="nav pull-right">
			<li><a><i class="icon-inbox icon-white"></i> 传单夹</a></li>
			<li class="divider-vertical"></li>
			{% if user.is_authenticated %}
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ user.first_name }}<b class="caret"></b></a>
				<ul class="dropdown-menu">
					<li><a href="#">个人资料</a></li>
					<li><a href="/logout/">登出</a></li>
				</ul>
			</li>
			{% else %}
			<li><a href="/login/renren/">人人登录</a></li>
			{% endif %}
		</ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
	
	<div class="container header">
	<div class="hero-unit">
		<div class="row">
			<div class="span4"><h1>环保集合令！</h1></div>
			<div class="span5">坐在寝室怎么看海报？又要派遣十人小队满清华贴海报、发传单？<br>海报被盖住或者撕掉了怎么办？每次印海报都是社团的大支出？<br>传单、海报看过就丢，能不能更加绿色环保？<br>清华<span class="badge badge-error">"有堵墙"</span>帮你 handle 以上问题! <a href="#">了解更多..</a> </div>
			<div class="span3 btn-submit">
				<a href="/submit/" class="btn btn-large">投递海报</a>
				<a href="#" class="btn btn-large disabled" title="传单功能将在beta1.2版本推出，敬请期待！">分发传单</a>
			</div>
		</div>
	</div>
    </div>
	
	{% block page_content %}{% endblock %}
	
	<div class="container footer">
		<hr>
		<p>Design and build with all the love in the world <a href="#">@Good Will Hackathon</a> by <a href="#">@HeliumChen</a>.<br>Code licensed under the <a href="http://www.apache.org/licenses/LICENSE-2.0">Apache License v2.0</a>. Powered by <a href="http://twitter.github.com/bootstrap/">Bootstrap</a> and <a href="http://sae.sina.com.cn/">Sina App Engine</a>.</p>
		<p>© 2012 <a href="#">"公益骇客风"</a>诞生作品 | 让每一个精彩的公益点子成为现实</p>
	</div>
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.js"></script>
	{% block extra_footer %}{% endblock %}
  </body>
</html>

youdu/core/templates/index.html
{% extends "base.html" %}
{% block title %}有堵墙 | 清华人的环保海报墙{% endblock %}
{% block page_content %}
    <div class="container timeline">
	<div class="row timeline-mark timeline-mark-current">
		<div class="span3">
		<h3>近期海报 | 至{{recent|date:"m.d"}}</h3>
		</div>
	</div>
	<div class="row timeline-box">
		<ul class="thumbnails">
		{% for event in recent_events %}
		<li class="span4">
			<div class="thumbnail">
				<a href="/posters/{{event.id}}/" title="{{event.title}}"><img src="{% if event.small_poster %}{{event.small_poster.url}}{% endif%}"></a>
				<div class="caption">
					<h5><a href="/posters/{{event.id}}" title="{{event.title}}">{{event.title}}</a></h5>
					<p><i class="icon-time"></i> {{event.start_time|date:"M d D"}} | <i class="icon-map-marker"></i> {{event.site}} | <i class="icon-heart"></i> 32人想去</p>
				</div>
			</div>
		</li>
		{% empty %}
		<p>nothing</p>
		{% endfor %}
		</ul>
	</div>
	<div class="row timeline-mark timeline-mark-normal">
		<div class="span3">
		<h3>未来海报 | 至{{later|date:"m.d"}}</h3>
		</div>
	</div>
	<div class="row timeline-mark timeline-mark-bottom"></div>
    </div> <!-- /container -->
{% endblock %}

youdu/core/templates/poster.html
{% extends "base.html" %}
{% block title %}活动名称 | 有堵墙,清华人的环保海报墙{% endblock %}
{% block page_content %}
    </div>
	<div class="container">
	<div class="page-header">
		<h1>{{event.title}}</h1>
	</div>
	<div class="span8 no-margin-left">
	<div class="thumbnail poster"><img src="{{event.poster.url}}"/></div>
	</div>
	<div class="span3">
		<div class="well">
			<p><i class="icon-time"></i> {{event.start_time}}</p>
			<p><i class="icon-map-marker"></i> {{event.site}}</p>
			<p><i class="icon-pencil"></i> 海报由 {{event.designer}} 设计</p>
			<p><i class="icon-heart"></i> 23 人想参加</p>
			<p><i class="icon-user"></i> {{event.user_post.first_name}} 发布</p>
			<p><i class="icon-info-sign"></i> <a href="{{event.link}}">详情请点击</a></p>
		</div>
		<p><button class="btn">我想参加</button> <button class="btn">海报好漂亮</button></p>
		<hr>
		<h3>二维码</h3>
		<hr>
		<h3>分享给朋友</h3>
		<p></p>
		<hr>
		<h3>想参加的童鞋</h3>
		<p>头像放这里</p>
	</div>
	</div> <!-- /container -->
{% endblock %}

youdu/core/templates/submit_poster.html
{% extends "base.html" %}
{% block title %}发出海报 | 有堵墙,清华人的环保海报墙{% endblock %}
{% block page_content %}
	<div class="container">
	<div class="span8">
		<form class="form-horizontal" enctype="multipart/form-data" method="POST" action="/submit/">
		{% csrf_token %}
			<fieldset>
			<legend>填写海报相关信息</legend>
			<div class="control-group {% if form.title.errors %}error{% endif %}">
				<label class="control-label" for="id_title">活动名称</label>
				<div class="controls">
					{{ form.title }}					
					<p class="help-block">{% if form.title.errors %}<div class="help-inline">{{form.title.errors}}</div><br>{% endif %}请填写海报对应活动的名称，简单明了的名称能够吸引更多人来浏览。别超过25字噢亲！</p>
				</div>
          		</div>
			<div class="control-group {% if form.type.errors %}error{% endif %}">
				<label class="control-label" for="id_type">活动类型</label>
				<div class="controls">
					{{ form.type }}
					{% if form.type.errors %}<p class="help-block"><div class="help-inline">{{form.type.errors}}</div></p>{% endif %}					
				</div>
			</div>
			<div class="control-group {% if form.start_time.errors %}error{% endif %}">
				<label class="control-label" for="id_start_time">活动时间</label>
				<div class="controls">
					{{ form.start_time }}
					{% if form.start_time.errors %}<p class="help-block"><div class="help-inline">{{form.start_time.errors}}</div></p>{% endif %}
				</div>
			</div>
			<div class="control-group {% if form.site.errors %}error{% endif %}">
				<label class="control-label" for="id_site">活动地点</label>
				<div class="controls">
					{{ form.site }}
					{% if form.site.errors %}<p class="help-block"><div class="help-inline">{{form.site.errors}}</div></p>{% endif %}
				</div>
			</div>
			<div class="control-group {% if form.link.errors %}error{% endif %}">
				<label class="control-label" for="id_link">详情链接</label>
				<div class="controls">
					{{ form.link }}
					<p class="help-block">{% if form.link.errors %}<div class="help-inline">{{form.link.errors}}</div><br>{% endif %}（可选）把相关的链接地址（如人人日志、博客日志或者相关主页地址）粘贴在这里吧。</p>
				</div>
			</div>
			<hr>
			<div class="control-group {% if form.poster.errors %}error{% endif %}">
				<label class="control-label" for="id_poster">上传海报</label>
				<div class="controls">
					{{ form.poster }}
					<p class="help-block">{% if form.poster.errors %}<div class="help-inline">{{form.poster.errors}}</div><br>{% endif %}建议使用不小于800*600像素的图片，支持jpg、jpeg、png、gif格式。<p>
				</div>
			</div>
			<div class="control-group {% if form.designer.errors %}error{% endif %}">
				<label class="control-label" for="id_designer">设计者名称</label>
				<div class="controls">
					{{ form.designer }}
					<p class="help-block">{% if form.designer.errors %}<div class="help-inline">{{form.designer.errors}}</div><br>{% endif %}向这些设计师致敬！</p>
				</div>
          		</div>
			<div class="form-actions">
				<button type="submit" class="btn btn-primary">发出海报</button>
				<a class="btn" href="/">取消</a>
			</div>
			</fieldset>
		</form>
	</div>
	<div class="span3">
		<h3>海报小Tips</h3>
		<ul>
			<li>存活周期</li>
			<li>排序功能</li>
			<li>统计功能</li>
			<li>必要的审核</li>
			<li>CC lisences</li>
		</ul>
		<p>出现问题，请及时联系等等等</p>
	</div>
	</div> <!-- /container -->
	
{% endblock %}
{% block extra_head %}<link href="/static/css/jquery.ui.all.css" rel="stylesheet">{% endblock %}
{% block extra_footer %}
<script src="/static/js/jquery-ui.min.js" type="text/javascript"></script>
<script src="/static/js/jquery.ui.datepicker-zh-CN.js" type="text/javascript"></script>
<script src="/static/js/datetimepicker.js" type="text/javascript"></script>
<script type="text/javascript">
$('#id_start_time').datetimepicker({
	timeOnlyTitle: 'Выберите время',
	timeText: '时间',
	hourText: '小时',
	minuteText: '分钟',
	currentText: '现在',
	closeText: '确认'
});
</script>

{% endblock %}